version: '3.8'

services:
  db:
    image: postgres:15
    container_name: football_pg
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: league
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


